"""
Currently the adjoint method is not implemented and so the params for Pubmed  are not correct as I have changed
adjoint to False, but kept all other hyperparameter settings.
"""
good_params_dict = {
  'Cora': {'M_nodes': 64, 'adaptive': False, 'add_source': True, 'adjoint': False, 'adjoint_method': 'adaptive_heun',
           'adjoint_step_size': 1, 'alpha': 1.0, 'alpha_dim': 'sc', 'att_samp_pct': 1, 'attention_dim': 128,
           'attention_norm_idx': 1, 'attention_rewiring': False, 'attention_type': 'scaled_dot', 'augment': False,
           'baseline': False, 'batch_norm': False, 'beltrami': True, 'beta_dim': 'sc', 'block': 'attention', 'cpus': 1,
           'data_norm': 'rw', 'dataset': 'Cora', 'decay': 0.00507685443154266, 'directional_penalty': None,
           'dropout': 0.17167167167167166, 'dt': 0.001, 'dt_min': 1e-05, 'epoch': 100, 'exact': True, 'fc_out': False,
           'feat_hidden_dim': 64, 'function': 'laplacian', 'gdc_avg_degree': 64, 'gdc_k': 64, 'gdc_method': 'ppr',
           'gdc_sparsification': 'topk', 'gdc_threshold': 0.01, 'gpus': 0.5, 'grace_period': 20, 'heads': 8,
           'heat_time': 3.0, 'hidden_dim': 80, 'input_dropout': 0.5, 'jacobian_norm2': None, 'kinetic_energy': None,
           'label_rate': 0.5, 'leaky_relu_slope': 0.2, 'lr': 0.01334134134134134, 'max_epochs': 1000, 'max_iters': 100,
           'max_nfe': 2000, 'method': 'leapfrog', 'metric': 'accuracy', 'mix_features': False,
           'name': 'cora_beltrami_splits', 'new_edges': 'random', 'no_alpha_sigmoid': False, 'not_lcc': True,
           'num_init': 1, 'num_samples': 1000, 'num_splits': 2, 'ode_blocks': 1, 'optimizer': 'adamax', 'patience': 100,
           'pos_enc_hidden_dim': 16, 'pos_enc_orientation': 'row', 'pos_enc_type': 'GDC', 'ppr_alpha': 0.05,
           'reduction_factor': 10, 'regularise': False, 'reweight_attention': False, 'rewire_KNN': False,
           'rewire_KNN_T': 'T0', 'rewire_KNN_epoch': 10, 'rewire_KNN_k': 64, 'rewire_KNN_sym': False, 'rewiring': None,
           'rw_addD': 0.02, 'rw_rmvR': 0.02, 'self_loop_weight': 1, 'sparsify': 'S_hat', 'square_plus': True,
           'step_size': 1, 'threshold_type': 'addD_rvR', 'time': 18.294754260552843, 'tol_scale': 821.9773048827274,
           'tol_scale_adjoint': 1.0, 'total_deriv': None, 'use_cora_defaults': False, 'use_flux': False,
           'use_labels': False, 'use_lcc': True, 'use_mlp': False},
  'Citeseer': {'M_nodes': 64, 'adaptive': False, 'add_source': True, 'adjoint': False,
               'adjoint_method': 'adaptive_heun', 'adjoint_step_size': 1, 'alpha': 1.0,
               'alpha_dim': 'sc', 'att_samp_pct': 1, 'attention_dim': 32, 'attention_norm_idx': 1,
               'attention_rewiring': False, 'attention_type': 'exp_kernel', 'augment': False,
               'baseline': False, 'batch_norm': False, 'beltrami': False, 'beta_dim': 'sc',
               'block': 'attention', 'cpus': 1, 'data_norm': 'rw', 'dataset': 'Citeseer',
               'decay': 0.1, 'directional_penalty': None, 'dropout': 0.7488085003122172, 'dt': 0.001,
               'dt_min': 1e-05, 'epoch': 250, 'exact': True, 'fc_out': False, 'feat_hidden_dim': 64,
               'function': 'laplacian', 'gdc_avg_degree': 64, 'gdc_k': 128, 'gdc_method': 'ppr',
               'gdc_sparsification': 'topk', 'gdc_threshold': 0.01, 'gpus': 1.0, 'grace_period': 20,
               'heads': 8, 'heat_time': 3.0, 'hidden_dim': 80, 'input_dropout': 0.6803233752085334,
               'jacobian_norm2': None, 'kinetic_energy': None, 'label_rate': 0.5,
               'leaky_relu_slope': 0.5825086997804176, 'lr': 0.00863585231323069, 'max_epochs': 1000,
               'max_iters': 100, 'max_nfe': 3000, 'method': 'dopri5', 'metric': 'accuracy',
               'mix_features': False, 'name': 'Citeseer_beltrami_1_KNN', 'new_edges': 'random',
               'no_alpha_sigmoid': False, 'not_lcc': True, 'num_class': 6, 'num_feature': 3703,
               'num_init': 2, 'num_nodes': 2120, 'num_samples': 400, 'num_splits': 0, 'ode_blocks': 1,
               'optimizer': 'adam', 'patience': 100, 'pos_enc_dim': 'row', 'pos_enc_hidden_dim': 16,
               'ppr_alpha': 0.05, 'reduction_factor': 4, 'regularise': False,
               'reweight_attention': False, 'rewire_KNN': False, 'rewire_KNN_epoch': 10,
               'rewire_KNN_k': 64, 'rewire_KNN_sym': False, 'rewiring': None, 'rw_addD': 0.02,
               'rw_rmvR': 0.02, 'self_loop_weight': 1, 'sparsify': 'S_hat', 'square_plus': True,
               'step_size': 1, 'threshold_type': 'addD_rvR', 'time': 7.874113442879092,
               'tol_scale': 2.9010446330432815, 'tol_scale_adjoint': 1.0, 'total_deriv': None,
               'use_cora_defaults': False, 'use_flux': False, 'use_labels': False, 'use_lcc': True,
               'use_mlp': False},
  'Pubmed': {'M_nodes': 64, 'adaptive': False, 'add_source': True, 'adjoint': False,
             'adjoint_method': 'adaptive_heun', 'adjoint_step_size': 1, 'alpha': 1.0,
             'alpha_dim': 'sc', 'att_samp_pct': 1, 'attention_dim': 16, 'attention_norm_idx': 0,
             'attention_rewiring': False, 'attention_type': 'cosine_sim', 'augment': False,
             'baseline': False, 'batch_norm': False, 'beltrami': False, 'beta_dim': 'sc',
             'block': 'attention', 'cpus': 1, 'data_norm': 'rw', 'dataset': 'Pubmed',
             'decay': 0.0018236722171703636, 'directional_penalty': None,
             'dropout': 0.07191100715473969, 'dt': 0.001, 'dt_min': 1e-05, 'epoch': 600,
             'exact': False, 'fc_out': False, 'feat_hidden_dim': 64, 'function': 'laplacian',
             'gdc_avg_degree': 64, 'gdc_k': 64, 'gdc_method': 'ppr', 'gdc_sparsification': 'topk',
             'gdc_threshold': 0.01, 'gpus': 1.0, 'grace_period': 20, 'heads': 1, 'heat_time': 3.0,
             'hidden_dim': 128, 'input_dropout': 0.5, 'jacobian_norm2': None, 'kinetic_energy': None,
             'label_rate': 0.5, 'leaky_relu_slope': 0.2, 'lr': 0.014669345840305131,
             'max_epochs': 1000, 'max_iters': 100, 'max_nfe': 5000, 'method': 'dopri5',
             'metric': 'test_acc', 'mix_features': False, 'name': None, 'new_edges': 'random',
             'no_alpha_sigmoid': False, 'not_lcc': True, 'num_init': 1, 'num_samples': 400,
             'num_splits': 8, 'ode_blocks': 1, 'optimizer': 'adamax', 'patience': 100,
             'pos_enc_dim': 'row', 'pos_enc_hidden_dim': 16, 'ppr_alpha': 0.05,
             'reduction_factor': 10, 'regularise': False, 'reweight_attention': False,
             'rewire_KNN': False, 'rewire_KNN_T': 'T0', 'rewire_KNN_epoch': 10, 'rewire_KNN_k': 64,
             'rewire_KNN_sym': False, 'rewiring': None, 'rw_addD': 0.02, 'rw_rmvR': 0.02,
             'self_loop_weight': 1, 'sparsify': 'S_hat', 'square_plus': True, 'step_size': 1,
             'threshold_type': 'addD_rvR', 'time': 12.942327880200853,
             'tol_scale': 1991.0688305523001, 'tol_scale_adjoint': 16324.368093998313,
             'total_deriv': None, 'use_cora_defaults': False, 'use_flux': False, 'use_labels': False,
             'use_lcc': True, 'use_mlp': False, 'folder': 'pubmed_linear_att_beltrami_adj2',
             'index': 0, 'run_with_KNN': False, 'change_att_sim_type': False, 'reps': 1,
             'max_test_steps': 100, 'no_early': False, 'earlystopxT': 5.0, 'pos_enc_csv': False,
             'pos_enc_type': 'GDC'}
}
